export const GET_SERVICES = 'GET_SERVICES'
export const ADD_SERVICE = 'ADD_SERVICE'
export const DELETE_SERVICE = 'DELETE_SERVICE'
export const UPDATE_SERVICE = 'UPDATE_SERVICE'
export const SET_SERVICE = 'SET_SERVICE'
export const CLEAR_SERVICE = 'CLEAR_SERVICE'
export const SERVICE_ERROR = 'SERVICE_ERROR'

export const GET_POSTS = 'GET_POSTS'
export const ADD_POST = 'ADD_POST'
export const DELETE_POST = 'DELETE_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const SET_POST = 'SET_POST'
export const CLEAR_POST = 'CLEAR_POST'
export const POST_ERROR = 'POST_ERROR'

export const GET_ABOUT = 'GET_ABOUT'
export const UPDATE_ABOUT = 'UPDATE_ABOUT'
export const ABOUT_ERROR = 'ABOUT_ERROR'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const SET_LOADING = 'SET_LOADING'
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'